(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-visited-mode t)
 '(base16-theme-256-color-source 'base16-shell)
 '(beacon-mode t)
 '(blink-cursor-mode nil)
 '(clang-format-style "Chromium")
 '(column-number-mode t)
 '(company-auto-commit t)
 '(company-auto-commit-chars nil)
 '(company-idle-delay 0)
 '(company-minimum-prefix-length 1)
 '(company-quickhelp-delay 0.2)
 '(company-quickhelp-mode t)
 '(company-show-numbers ''t)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-flip-when-above t)
 '(css-indent-offset 2)
 '(custom-safe-themes
   '("a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "1e7e097ec8cb1f8c3a912d7e1e0331caeed49fef6cff220be63bd2a6ba4cc365" "fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" default))
 '(default-frame-alist
    '((fullscreen . maximized)
      (font . "-JB-JetBrains Mono-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1")
      (line-spacing . 0.2)))
 '(editorconfig-mode t)
 '(eldoc-idle-delay 0)
 '(elpy-modules
   '(elpy-module-company elpy-module-eldoc elpy-module-pyvenv elpy-module-highlight-indentation elpy-module-yasnippet elpy-module-django elpy-module-sane-defaults))
 '(elpy-rpc-python-command "python3")
 '(exec-path-from-shell-arguments '("-l"))
 '(fill-column 100)
 '(flycheck-checker-error-threshold 1000)
 '(flycheck-clang-language-standard "c++2a")
 '(flycheck-disabled-checkers '(javascript-jshint))
 '(flycheck-indication-mode nil)
 '(global-auto-revert-mode t)
 '(global-company-mode t)
 '(global-diff-hl-mode t)
 '(global-flycheck-mode t)
 '(global-hl-line-mode nil)
 '(global-subword-mode t)
 '(global-undo-tree-mode t)
 '(global-whitespace-cleanup-mode t)
 '(indent-tabs-mode nil)
 '(ivy-height 25)
 '(js-indent-level 2)
 '(js-switch-indent-offset 2)
 '(js2-bounce-indent-p t)
 '(js2-mode-show-parse-errors nil)
 '(js2-mode-show-strict-warnings nil)
 '(lsp-auto-guess-root t)
 '(lsp-clients-typescript-server-args '("--stdio" "--tsserver-log-file" "/dev/stderr"))
 '(lsp-eldoc-render-all t)
 '(lsp-enable-file-watchers nil)
 '(lsp-eslint-auto-fix-on-save t)
 '(lsp-eslint-package-manager "yarn")
 '(lsp-headerline-breadcrumb-enable nil)
 '(lsp-ui-doc-enable nil)
 '(lsp-ui-sideline-enable nil)
 '(menu-bar-mode nil)
 '(pixel-scroll-mode t)
 '(prelude-whitespace nil)
 '(prescient-persist-mode t)
 '(projectile-completion-system 'default)
 '(projectile-mode t nil (projectile))
 '(python-indent-def-block-scale 1)
 '(python-shell-extra-pythonpaths '("~/.local/venvs"))
 '(pyvenv-virtualenvwrapper-python "~/.local/share/virtualenvs/virtualenvwrapper/bin/python")
 '(read-process-output-max (* 1024 1024) t)
 '(recentf-max-saved-items 500)
 '(recentf-mode t)
 '(replace-char-fold t)
 '(require-final-newline t)
 '(safe-local-variable-values '((encoding . utf-8)))
 '(save-place-mode t nil (saveplace))
 '(scroll-bar-mode nil)
 '(scroll-preserve-screen-position t)
 '(search-default-mode 'char-fold-to-regexp)
 '(selectrum-mode t)
 '(selectrum-prescient-mode t)
 '(sentence-end-double-space nil)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(smartparens-global-mode t)
 '(sp-autoskip-closing-pair 'always)
 '(sp-base-key-bindings 'paredit)
 '(straight-use-package-by-default t)
 '(tab-always-indent 'complete)
 '(tool-bar-mode nil)
 '(truncate-lines t)
 '(typescript-auto-indent-flag nil)
 '(typescript-indent-level 2)
 '(uniquify-buffer-name-style 'forward nil (uniquify))
 '(uniquify-ignore-buffers-re "\"^\\\\*\"")
 '(uniquify-separator "\"/\"")
 '(volatile-highlights-mode t)
 '(vterm-kill-buffer-on-exit t)
 '(web-mode-attr-indent-offset 2)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-optional-tags t)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-script-padding 2)
 '(web-mode-style-padding 2)
 '(which-key-mode t)
 '(whitespace-line-column nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
