(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-save-visited-mode t)
 '(base16-theme-256-color-source 'base16-shell)
 '(clang-format-style "Chromium")
 '(column-number-mode t)
 '(company-auto-commit t)
 '(company-auto-commit-chars nil)
 '(company-idle-delay 0)
 '(company-minimum-prefix-length 1)
 '(company-quickhelp-delay 0.2)
 '(company-quickhelp-mode t)
 '(custom-safe-themes
   '("a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "1e7e097ec8cb1f8c3a912d7e1e0331caeed49fef6cff220be63bd2a6ba4cc365" "fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" default))
 '(default-frame-alist '((line-spacing . 0.2)))
 '(eldoc-idle-delay 0)
 '(elpy-modules
   '(elpy-module-company elpy-module-eldoc elpy-module-pyvenv elpy-module-highlight-indentation elpy-module-yasnippet elpy-module-django elpy-module-sane-defaults))
 '(elpy-rpc-python-command "python3")
 '(fill-column 100)
 '(flycheck-checker-error-threshold 1000)
 '(flycheck-clang-language-standard "c++2a")
 '(flycheck-disabled-checkers '(javascript-jshint))
 '(flycheck-indication-mode nil)
 '(global-company-mode t)
 '(global-flycheck-mode t)
 '(global-hl-line-mode nil)
 '(global-subword-mode t)
 '(global-whitespace-cleanup-mode t)
 '(ivy-height 25)
 '(js-indent-level 2)
 '(js-switch-indent-offset 2)
 '(js2-bounce-indent-p t)
 '(js2-mode-show-parse-errors nil)
 '(js2-mode-show-strict-warnings nil)
 '(lsp-auto-guess-root t)
 '(lsp-clients-typescript-server-args '("--stdio" "--tsserver-log-file" "/dev/stderr"))
 '(lsp-eldoc-render-all t)
 '(lsp-enable-file-watchers nil)
 '(lsp-eslint-auto-fix-on-save t)
 '(lsp-eslint-package-manager "yarn")
 '(lsp-headerline-breadcrumb-enable nil)
 '(lsp-ui-doc-enable nil)
 '(lsp-ui-sideline-enable nil)
 '(package-selected-packages
   '(ace-window add-node-modules-path alchemist anaconda-mode anzu avy base16-theme beacon browse-kill-ring cargo cfrs chruby clang-format coffee-mode company company-anaconda company-emoji company-go company-lsp company-quickhelp company-tabnine company-terraform counsel crux cython-mode dap-mode dash dash-functional diff-hl diminish discover-my-major dockerfile-mode easy-kill editorconfig elisp-slime-nav elixir-mode elpy erlang exec-path-from-shell flycheck flycheck-inline flycheck-mypy flycheck-rust geiser gitconfig-mode gitignore-mode go-eldoc go-mode go-projectile god-mode google-c-style gotest graphql-mode haskell-mode hcl-mode helm helm-projectile highlight-indentation ivy ivy-prescient jest json-mode less-css-mode let-alist lsp-java lsp-javascript-typescript lsp-mode lsp-treemacs lsp-ui magit magit-popup markdown-mode move-text multiple-cursors nginx-mode operate-on-number pipenv posframe prescient projectile protobuf-mode python pyvenv racer ripgrep rust-mode rustfmt scss-mode selectrum selectrum-prescient smartparens smartrep sort-words super-save swiper terraform-mode theme-changer toml-mode transient treemacs typescript-mode undo-tree use-package volatile-highlights vterm vterm-toggle web-mode which-key whitespace-cleanup-mode yaml-mode yari zop-to-char))
 '(pixel-scroll-mode t)
 '(prelude-whitespace nil)
 '(prescient-persist-mode t)
 '(projectile-completion-system 'default)
 '(python-indent-def-block-scale 1)
 '(python-shell-extra-pythonpaths '("~/.local/venvs"))
 '(pyvenv-virtualenvwrapper-python "~/.local/share/virtualenvs/virtualenvwrapper/bin/python")
 '(read-process-output-max (* 1024 1024) t)
 '(replace-char-fold t)
 '(safe-local-variable-values '((encoding . utf-8)))
 '(save-place-mode t nil (saveplace))
 '(scroll-bar-mode nil)
 '(search-default-mode 'char-fold-to-regexp)
 '(sentence-end-double-space nil)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(smartparens-global-mode t)
 '(tool-bar-mode nil)
 '(truncate-lines t)
 '(typescript-auto-indent-flag nil)
 '(typescript-indent-level 2)
 '(uniquify-buffer-name-style 'forward nil (uniquify))
 '(vterm-kill-buffer-on-exit t)
 '(web-mode-attr-indent-offset 2)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-optional-tags t)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-script-padding 2)
 '(web-mode-style-padding 2)
 '(whitespace-line-column nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:slant normal :weight normal :height 98 :width normal :foundry "nil" :family "JetBrains Mono")))))
